#ifndef QRESOURCEGUARD_HPP
#define QRESOURCEGUARD_HPP

#include <memory>

/**
 *@brief collection of the functions which designed for
 * guarding the resources of Qt
 */

namespace qh{

/**
 *@brief provide exception safe initialization of the
 * Widget generated by QtDesigner
 *@param Target the type need to protect
 *@param Parent type of the parent belong to the Target
 *@param parent the parent
 */
template<typename Target, typename Parent>
Target* guard_setup_ui(Parent *parent)
{
    std::unique_ptr<Target> temp(new Target);
    temp->setupUi(parent);

    return temp.release();
}

}

#endif // QRESOURCEGUARD_HPP
